### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Cinetielle** [csoulain/porousMedia4Foam#2]
I have several error during compilation (OpenFOAM v7):

./Allwmake
porousInterfaceProperties & porousImmiscibleIncompressiveTwoPhaseMixture:
![image](https://user-images.githubusercontent.com/70530223/204522091-945d903c-c296-490e-99b4-e1119f747c59.png)

toolsGIS:
![image](https://user-images.githubusercontent.com/70530223/204522008-c70c4a09-177e-4676-bfd0-606cb8964645.png)

porousBoundaryConditions:
![image](https://user-images.githubusercontent.com/70530223/204521942-060a1e88-3060-4002-8da7-f149df11f508.png)

dbsSimpleFoam & dbsFoam
![image](https://user-images.githubusercontent.com/70530223/204521880-f376dd17-59ef-4985-8b2d-0d23c0b6a562.png)

hybridPorousFoam
![image](https://user-images.githubusercontent.com/70530223/204521792-da04f050-05c6-4ecf-8027-afa4d1f9a651.png)

Do you have any advice for me ?

Thank you for all,

**Comment by csoulain** [comment]
Hi,


It should be compiled with OpenFOAM 8 for the master version, and OpenFOAM
10 for the v10 branch.

Best,

**Comment by Cinetielle** [comment]
Many thanks for your answer ! 

Tests cases are all ok (master & OpenFoam 8) !

However, I have this information repeated several times:
cannot find -lporousModels

and in the log.darcyFoam (tutorials/darcyFoam-tutorials/SPE10)
I have:
 ./run: 93: ./run: darcyFoam: not found

the same for log.impesFoam (tutorials/impesFoam-tutorials/injectionExtraction/extraction)

Despite tests, I think the installation failed right ?

In the platforms/linux64GccDPInt32Opt/lib i have:
![image](https://user-images.githubusercontent.com/70530223/204542918-6074dff3-1dcb-4f3d-8047-4c5893e0c87c.png)

and the /bin is empty !

Maybe the first problems come from here ?
![image](https://user-images.githubusercontent.com/70530223/204544122-b2024e4a-c8c9-4ba9-94ef-79f5ca3445da.png)

**Comment by Cinetielle** [comment]
Ok,

I have installed pm4f on another computer and all is fine,

Maybe the error come from 'anaconda3/.../gcc/...' or something related to path.

Someone had a similar problem:
https://www.cfd-online.com/Forums/openfoam-installation/245070-lib-files-issues-of2206-ubuntu-22-04-wsl2.html
